### ISSUE TITLE
update to latest version

### ISSUE THREAD

**Issue by MrMinimal64** [conda-forge/timezonefinder-feedstock#2]
I plan on releasing v2.1.2 today (because a new version of the data got released).
Since the data set currently in use in the feedstock (tz_world) is outdated an update would make sense.

**Comment by MrMinimal64** [comment]
I just published timezonefinder3.0.0
It uses the newest available data set of timezone boundary data.

**Comment by snowman2** [comment]
Fixed by PR #5
