### ISSUE TITLE
Conda auto build is failing

### ISSUE THREAD

**Issue by MrMinimal64** [conda-forge/timezonefinder-feedstock#9]
#8 is not being auto merged, because the CircleCI build is failing with this error:

```
.../python3.7/site-packages/timezonefinder/timezonefinder.py", line 10, in <module>
    from pkg_resources import resource_stream
ModuleNotFoundError: No module named 'pkg_resources'
```
The package `pkg_resources` is not being used anywhere in `timezonefinder`. Does anyone know where this comes from and how to fix it?

**Comment by snowman2** [comment]
It looks like you are using it here: https://github.com/MrMinimal64/timezonefinder/blob/master/timezonefinder/timezonefinder.py#L10

Would this be a possible solution for you:
https://importlib-resources.readthedocs.io/en/latest/

Thoughts?

**Comment by MrMinimal64** [comment]
I don't get it. the newest pull request #8 is still getting this error:
```

python3.6/site-packages/timezonefinder/timezonefinder.py", line 10, in <module>
    from pkg_resources import resource_stream
```

Even though in https://github.com/MrMinimal64/timezonefinder/blob/master/timezonefinder/timezonefinder.py#L10
there clearly is no usage of `pkg_resources`.
Why isnt this pull request getting a new ID and why is it still using the old code?

**Comment by snowman2** [comment]
PR #8 was created based on the previous version. If the new version is on pypi, it should automatically create a new PR soon.

**Comment by MrMinimal64** [comment]
That makes sense. I will upload the newest version to pypi now.

**Comment by MrMinimal64** [comment]
#10 now fails with this error:

```
from importlib_resources import open_binary
ModuleNotFoundError: No module named 'importlib_resources'
```

**Comment by MrMinimal64** [comment]
#10 now fails with this error:

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/timezonefinder_1541005281767/test_tmp/run_test.py", line 11, in <module>
    import timezonefinder.functional
ModuleNotFoundError: No module named 'timezonefinder.functional'
```

**Comment by snowman2** [comment]
It passed and the build should be completed soon. Thanks!
